name: aligo
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  intl: ^0.20.2
  sqflite_common_ffi: ^2.3.5
  file_picker: ^10.1.2
  image_picker: ^1.1.2
  #  charts_flutter: ^0.12.0
  syncfusion_flutter_charts: ^29.1.40
  path:
  mobile_scanner: ^7.0.0
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  firebase_storage:
  excel: ^4.0.6
  signature:


#dependency_overrides:
# add override of charts_flutter
#  charts_flutter:
#    git:
#      url: https://github.com/kennenfromchina/charts.git
#      path: charts_flutter
#      ref: fix_flutter3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/mof_logo.jpeg"
  android: true
  ios: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/mof_logo.jpeg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Italic.ttf