// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_pe4qN5JLZC6-YpaLokU2fB6doMkb5Gs',
    appId: '1:1059464837496:web:81e27b017d1e77b4af708d',
    messagingSenderId: '1059464837496',
    projectId: 'moh-aligo',
    authDomain: 'moh-aligo.firebaseapp.com',
    storageBucket: 'moh-aligo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-JAbkWgsIfs3CKWuBq153KluI8jAtDck',
    appId: '1:1059464837496:android:00897ebb2d8c18b5af708d',
    messagingSenderId: '1059464837496',
    projectId: 'moh-aligo',
    storageBucket: 'moh-aligo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqm5grnt6CNbsX1GW1S3lWLQm9WqadLDA',
    appId: '1:1059464837496:ios:5d9e5b5299f00fc2af708d',
    messagingSenderId: '1059464837496',
    projectId: 'moh-aligo',
    storageBucket: 'moh-aligo.appspot.com',
    iosBundleId: 'ng.sysoftware.aligo',
  );
}
